# Generated by Django 3.1.2 on 2020-11-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='reorder_level',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
